# minimal mistake보고 config 나머지 채워넣기
locale                   : "ko-KR"
name                     : "winterbloooom (한은기)"
url                      : "https://winterbloooom.github.io"
repository               : "https://github.com/winterbloooom/winterbloooom.github.io"

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-NDR0GLWHWZ"
    anonymize_ip         : # true, false (default)

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  math_engine: mathjax
  # hard_wrap: false
  # auto_ids: true
  # footnote_nr: 1
  # entity_output: as_char
  # toc_levels: 1..6
  # smart_quotes: lsquo,rsquo,ldquo,rdquo
  # enable_coderay: false


timezone: Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
      mathjax: true
      toc: false
      # teaser: "/assets/images/horizontal1.jpg"
      # TODO 카테고리 별 기본 이미지 정하기